name: Jekyll IS Publisher

description: Publish a pre-built website (or individual files) on GitHub Pages

branding:
  icon: 'upload-cloud'
  color: 'white'

inputs:
  label: 
    description: Text label for commit messages and notifications
    required: true
  sync-dir:
    description: Directory of website files for publish
    required: false
  copy-dir:
    description: Additional files for publish
    required: false
  github-actor:
    description: GitHub Actor for publish changes
    required: true
  github-token:
    description: GitHub Token for publish changes
    required: true
  pages-repository:
    description: Repository with GitHub Pages branch
    required: true
  pages-branch:
    description: "Branch with Pages to push (default: 'gh-pages')"
    required: false
  telegram-bot-token:
    description: Telegram bot token for notification
    required: false
  telegram-user-id:
    description: Telegram user ID for notification
    required: false

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y rsync
    - name: Fetch, Update & Publish
      shell: bash
      env:
        LABEL: ${{ inputs.label }}
        SYNC_DIR: ${{ inputs.sync-dir }}
        COPY_DIR: ${{ inputs.copy-dir }}
        GH_ACTOR: ${{ inputs.github-actor }}
        GH_TOKEN: ${{ inputs.github-token }}
        PGS_REPO: ${{ inputs.pages-repository }}
        PGS_BRANCH: ${{ inputs.pages-branch }}
        TG_TOKEN: ${{ inputs.telegram-bot-token }}
        TG_USER_ID: ${{ inputs.telegram-user-id }}
      run: |
        set -euo pipefail
        REPO="https://github.com/${PGS_REPO}.git"
        BRANCH=${PGS_BRANCH:-gh-pages}
        git config --global url."https://${GH_ACTOR}:${GH_TOKEN}@github.com/".insteadOf "https://github.com/"
        git clone --branch ${BRANCH} --single-branch ${REPO} gh-pages
        if [ -n "$SYNC_DIR" ]; then
          rsync -a --delete --exclude='.git/' "$SYNC_DIR/" "gh-pages/"
        fi
        if [ -n "$COPY_DIR" ]; then
          rsync -a --exclude='.git/' "$COPY_DIR/" "gh-pages/"
        fi
        cd gh-pages
        git config user.name "${GH_ACTOR}"
        git config user.email "${GH_ACTOR}@users.noreply.github.com"
        git add .
        if git diff --cached --quiet; then
          echo "No changes. Nothing to do."
        else
          MSG="Publishing by ${LABEL} @ $(date)"
          git commit -m "$MSG"
          git push --force ${REPO} ${BRANCH}:${BRANCH}
          if [ -n "$TG_TOKEN" ] && [ -n "$TG_USER_ID" ]; then
            NEWLINE=$'\n'
            SHOW=$(git show --pretty="" --name-status HEAD)
            SHOW_LINES=$(echo "$SHOW" | wc -l)
            if [ "$SHOW_LINES" -gt 20 ]; then
              SHOW="$(echo "$SHOW" | head -20)$NEWLINE..."
            fi
            TEXT=$(echo "${MSG}${NEWLINE}${NEWLINE}${SHOW_LINES} file(-s) changed:${NEWLINE}```git${NEWLINE}${SHOW}${NEWLINE}```${NEWLINE}" | sed 's/\\/\\\\/g; s/"/\\"/g; s/[_*[\]()~`>#+\-=|{}.!]/\\&/g')
            JSON="{\"chat_id\":\"$TG_USER_ID\",\"text\":\"$TEXT\",\"parse_mode\":\"MarkdownV2\"}"
            curl -X POST "https://api.telegram.org/bot${TG_TOKEN}/sendMessage" -H "Content-Type: application/json" -d "${JSON}"
          fi
        fi
