name: Jekyll IS Publisher

description: Publish a pre-built website (or individual files) on GitHub Pages

branding:
  icon: 'upload-cloud'
  color: 'white'

inputs:
  label: 
    description: Text label for commit messages and notifications
    required: true
  sync-dir:
    description: Directory of website files for publish
    required: false
  copy-dir:
    description: Additional files for publish
    required: false
  github-actor:
    description: GitHub Actor for publish changes
    required: true
  github-token:
    description: GitHub Token for publish changes
    required: true
  pages-repository:
    description: Repository with GitHub Pages branch
    required: true
  pages-branch:
    description: "Branch with Pages to push (default: 'gh-pages')"
    required: false
  telegram-bot-token:
    description: Telegram bot token for notification
    required: false
  telegram-user-id:
    description: Telegram user ID for notification
    required: false

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y rsync
    - name: Fetch, Update & Publish
      shell: bash
      run: |
        set -euo pipefail
        ACTOR=${INPUT_GITHUB_ACTOR:-github-actions[bot]}
        echo "Actor: ${ACTOR}"
        BRANCH=${INPUT_PAGES_BRANCH:-gh-pages}
        git config --global url."https://${ACTOR}:${INPUT_GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
        git clone --branch ${BRANCH} --single-branch ${INPUT_PAGES_REPOSITORY} gh-pages
        if [ -n "$INPUT_SYNC_DIR" ]; then
          rsync -a --delete --exclude='.git/' "$INPUT_SYNC_DIR/" "gh-pages/"
        fi
        if [ -n "$INPUT_COPY_DIR" ]; then
          rsync -a --exclude='.git/' "$INPUT_COPY_DIR/" "gh-pages/"
        fi
        cd gh-pages
        git config user.name "${ACTOR}"
        git config user.email "${ACTOR}@users.noreply.github.com"
        git add .
        if git diff --cached --quiet; then
          echo "No changes. Nothing to do."
        else
          MSG="Publishing by ${INPUT_LABEL} @ $(date)"
          git commit -m "$MSG"
          git push --force ${INPUT_PAGES_REPOSITORY} ${BRANCH}:${BRANCH}
          if [ -n "$INPUT_TELEGRAM_BOT_TOKEN" ] && [ -n "$INPUT_TELEGRAM_USER_ID" ]; then
            NEWLINE=$'\n'
            SHOW=$(git show --pretty="" --name-status HEAD)
            SHOW_LINES=$(echo "$SHOW" | wc -l)
            if [ "$SHOW_LINES" -gt 20 ]; then
              SHOW="$(echo "$SHOW" | head -20)$NEWLINE..."
            fi
            TEXT=$(echo "${MSG}${NEWLINE}${NEWLINE}${SHOW_LINES} file(-s) changed:${NEWLINE}```git${NEWLINE}${SHOW}${NEWLINE}```${NEWLINE}" | sed 's/\\/\\\\/g; s/"/\\"/g; s/[_*[\]()~`>#+\-=|{}.!]/\\&/g')
            JSON="{\"chat_id\":\"$INPUT_TELEGRAM_USER_ID\",\"text\":\"$TEXT\",\"parse_mode\":\"MarkdownV2\"}"
            curl -X POST "https://api.telegram.org/bot${INPUT_TELEGRAM_BOT_TOKEN}/sendMessage" -H "Content-Type: application/json" -d "${JSON}"
          fi
        fi
